DROP TABLE RENTAL;
DROP TABLE USERS_ROLES;
DROP TABLE BOOK;
DROP TABLE USERS;

CREATE TABLE USERS
(
	userid INT NOT NULL,
	name VARCHAR(255) NOT NULL PRIMARY KEY,
	password VARCHAR(255) NOT NULL,
	roles VARCHAR(255)
);

CREATE TABLE BOOK
(
	bookid INT NOT NULL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	author VARCHAR(255) NOT NULL,
	image BLOB NOT NULL,
	contenttype VARCHAR(255) NOT NULL,
	availablecopies INT NOT NULL
);

CREATE TABLE RENTAL
(
	rentalid INT NOT NULL PRIMARY KEY,
	bookid INT NOT NULL,
	username VARCHAR(255) NOT NULL,
	rentaldate DATE NOT NULL,
	returndate DATE NOT NULL,
	status VARCHAR(255) NOT NULL,
   FOREIGN KEY(username) REFERENCES USERS(name),
   FOREIGN KEY(bookid) REFERENCES BOOK(bookid)
);

CREATE TABLE USERS_ROLES
(
	users_name VARCHAR(255) NOT NULL PRIMARY KEY,
	roles VARCHAR(255) NOT NULL,
	FOREIGN KEY(users_name) REFERENCES USERS(name)
);

INSERT INTO USERS (USERID, NAME, PASSWORD, ROLES) 
VALUES (1, 'Csabi', 'aaa', 'ADMIN'), (2, 'Lilla', 'bbb', 'CUSTOMER'), (3, 'Gergely', 'ccc', 'ADMIN'), (4, 'Melinda', 'ddd', 'CUSTOMER');

INSERT INTO USERS_ROLES (USERS_NAME, ROLES)
VALUES ('Csabi', 'ADMIN'), ('Lilla', 'CUSTOMER'), ('Gergely', 'ADMIN'), ('Melinda', 'CUSTOMER');

